Teach9/urls.py
"""
Definition of urls for Teach9.
"""

from datetime import datetime
from django.conf.urls import include, url
import django.contrib.auth.views
from django.conf import settings
from django.conf.urls.static import static

import app.forms
import app.views

application_title = settings.COURSE_SITE_TITLE
# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
				'application':application_title,
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    url(r'^admin/', include(admin.site.urls)),

	url(r'^courses/', include("courses.urls", namespace="courses")),

	url(r'^profile/$', app.views.profile, name="profile"),
	url(r'^profile/create/$', app.views.create_profile, name="create_profile"),
	url(r'^profile/edit/$', app.views.edit_profile, name="edit_profile"),
	url(r'^profile/editpass/$', django.contrib.auth.views.password_change, name="edit_password"),
	url(r'^profile/$', app.views.profile, name='password_change_done'),

]

courses/urls.py
from django.conf.urls import url
import django.contrib.auth.views

from .views import (
	course_create,
    course_list,
    course_detail,
	course_update,
	course_delete,
	lesson_create,
	lesson_detail,
	lesson_update,
	lesson_delete,
	activity_create,
	activity_vote,
	activity_detail,
	activity_update,
	activity_delete,
	assignment_list,
	assignment_create,
	assignment_detail,
	assignment_update,
	assignment_delete,
    )

urlpatterns = [
    url(r'^$', course_list, name='course_list'),
    url(r'^create/$', course_create, name='course_create'),
    url(r'^(?P<course>[\w-]+)/$', course_detail, name='course_detail'),
	url(r'^(?P<course>[\w-]+)/edit/$', course_update, name='course_update'),
	url(r'^(?P<course>[\w-]+)/delete/$', course_delete, name="course_delete"),
	url(r'^(?P<course>[\w-]+)/create/$', lesson_create, name="lesson_create"),
	url(r'^(?P<course>[\w-]+)/assignments/$', assignment_list, name="assignment_list"),
	url(r'^(?P<course>[\w-]+)/assignments/create/$', assignment_create, name="assignment_create"),
	url(r'^(?P<course>[\w-]+)/assignments/(?P<assignment>[\w-]+)/$', assignment_detail, name="assignment_detail"),
	url(r'^(?P<course>[\w-]+)/assignments/(?P<assignment>[\w-]+)/edit/$', assignment_update, name="assignment_update"),
	url(r'^(?P<course>[\w-]+)/assignments/(?P<assignment>[\w-]+)/delete/$', assignment_delete, name="assignment_delete"),
	url(r'^(?P<course>[\w-]+)/(?P<lesson>[\w-]+)/$', lesson_detail, name="lesson_detail"),
	url(r'^(?P<course>[\w-]+)/(?P<lesson>[\w-]+)/edit/$', lesson_update, name="lesson_update"),
	url(r'^(?P<course>[\w-]+)/(?P<lesson>[\w-]+)/delete/$', lesson_delete, name="lesson_delete"),
	url(r'^(?P<course>[\w-]+)/(?P<lesson>[\w-]+)/createactiv/$', activity_create, name="activity_create"),
	url(r'^(?P<course>[\w-]+)/(?P<lesson>[\w-]+)/(?P<activity>[\w-]+)/$', activity_detail, name="activity_detail"),
	url(r'^(?P<course>[\w-]+)/(?P<lesson>[\w-]+)/(?P<activity>[\w-]+)/vote/$', activity_vote, name="activity_vote"),
	url(r'^(?P<course>[\w-]+)/(?P<lesson>[\w-]+)/(?P<activity>[\w-]+)/edit/$', activity_update, name="activity_update"),
	url(r'^(?P<course>[\w-]+)/(?P<lesson>[\w-]+)/(?P<activity>[\w-]+)/delete/$', activity_delete, name="activity_delete"),
]

git/teach9/Teach9/urls.py
"""
Definition of urls for Teach9.
"""

from datetime import datetime
from django.conf.urls import include, url
import django.contrib.auth.views
from django.conf import settings
from django.conf.urls.static import static

import app.forms
import app.views

application_title = settings.COURSE_SITE_TITLE
# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
				'application':application_title,
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    url(r'^admin/', include(admin.site.urls)),

	url(r'^courses/', include("courses.urls", namespace="courses")),

	url(r'^profile/$', app.views.profile, name="profile"),
	url(r'^profile/create/$', app.views.create_profile, name="create_profile"),
	url(r'^profile/edit/$', app.views.edit_profile, name="edit_profile"),
	url(r'^profile/editpass/$', django.contrib.auth.views.password_change, name="edit_password"),
	url(r'^profile/$', app.views.profile, name='password_change_done'),

]

templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - {{ application }}</title>
	{% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui/smoothness/jquery-ui.min.css' %}"/> 
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>

    {% load static %}
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">{{ application }}</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'courses:course_list' %}">Courses</a></li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'profile' %}">My Profile</a></li>
                    {% endif %}
                    {% if request.user.is_staff %}
                    <li><a href="{% url 'create_profile' %}">Create Student Profile</a></li>
                    {% endif %}
                    {% if request.user.is_superuser %}
                    <li><a href="{% url "admin:index" %}">Admin</a></li>
                    {% endif %}
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
            <div class="navbar-collapse collapse">

            </div>
        </div>
    </div>
    {% load django_bootstrap_breadcrumbs %}
           {% block breadcrumbs %}
       {% endblock %}

    <div class="container body-content">
                {% render_breadcrumbs %}
{% block content %}

        {% endblock %}
        <footer>
        </footer>
    </div>
{% block scripts %}{% endblock %}
     
</body>
</html>